export default {
	roles: ['Administrador', 'Gerencial', 'Consultor'],
	users: [
		{
			name: 'Administrador',
			password: '@Admin',
			email: 'admin@zsystems.com.br',
			role: 'Administrador',
			status: 'active',
		},
		{
			name: 'Rodrigo Henrique Sobrinho',
			password: '@Rodrigo321',
			email: 'rodrigo@zsystems.com.br',
			role: 'Administrador',
			status: 'active',
		},
		{
			name: 'Dayglor',
			password: '@Dayglor321',
			email: 'dayglor@zsystems.com.br',
			role: 'Administrador',
			status: 'active',
		},
		{
			name: 'Renan',
			password: '@Renan321',
			email: 'renan.costa@zsystems.com.br',
			role: 'Administrador',
			status: 'active',
		},
		{
			name: 'Dev',
			password: '@Dev321',
			email: 'dev@zsystems.com.br',
			role: 'Administrador',
			status: 'active',
		},
	],
	actions: [
		{ name: 'BillsToPay', parent: null },
		{ name: 'Clients', parent: null },
		{ name: 'Invoices', parent: null },
		{ name: 'Payments', parent: null },
		{ name: 'Products', parent: null },
		{ name: 'Reports', parent: null },
		{ name: 'Sales', parent: null },
		{ name: 'Scores', parent: null },
		{ name: 'ShippingCompany', parent: null },
		{ name: 'get-sales-by-consultant', parent: null },

		{ name: 'approve-pre-register', parent: 'Users' },
		{ name: 'get-bills-to-pay', parent: 'BillsToPay' },
		{ name: 'get-clients', parent: 'Clients' },
		{ name: 'get-invoices', parent: 'Invoices' },
		{ name: 'get-invoices-configurations', parent: 'Invoices' },
		{ name: 'get-payments', parent: 'Payments' },
		{ name: 'get-products', parent: 'Products' },
		{ name: 'register-product-category', parent: 'Products' },
		{ name: 'get-product-category', parent: 'Products' },
		{ name: 'get-reports', parent: 'Reports' },
		{ name: 'get-sales', parent: 'Sales' },
		{ name: 'get-sale', parent: 'Sales' },
		{ name: 'get-scores', parent: 'Scores' },
		{ name: 'get-scores-configurations', parent: 'Scores' },
		{ name: 'get-users', parent: 'Users' },
		{ name: 'get-users-pre-register', parent: 'Users' },
		{ name: 'register-bills-to-pay', parent: 'BillsToPay' },
		{ name: 'register-clients', parent: 'Clients' },
		{ name: 'register-invoices', parent: 'Invoices' },
		{ name: 'register-products', parent: 'Products' },
		{ name: 'register-sales', parent: 'Sales' },
		{ name: 'register-users', parent: 'Users' },
		{ name: 'scores-find', parent: 'Scores' },
		{ name: 'scores-history', parent: 'Scores' },
		{ name: 'register-product-category', parent: 'Products' },
		{ name: 'shipping-company-list', parent: 'ShippingCompany' },
		// { name: 'shipping-company-register', parent: 'ShippingCompany' },
	],
	// products: [
	// 	{
	// 		id: '916b9bd507f1410a96a637b483906da1',
	// 		name: 'Consulta de score',
	// 		product_code: 'CS',
	// 		sku: '12345',
	// 		stock: 'N',
	// 		cost_price: '1000',
	// 		product_category_id: 'abc12345',
	// 	},
	// 	{
	// 		id: 'f2ffnju8u44dsfs112fhjytytf46b5b164',
	// 		name: 'Emissão de nota fiscal',
	// 		product_code: 'ENF',
	// 		sku: '12345',
	// 		stock: 'N',
	// 		cost_price: '2500',
	// 		product_category_id: 'abc12345',
	// 	},
	// 	{
	// 		id: 'eea1551a7a27430b8e3d0972eb3bc12a',
	// 		name: 'Mensalidade',
	// 		product_code: 'MS',
	// 		sku: '12345',
	// 		stock: 'N',
	// 		cost_price: '1500',
	// 		product_category_id: 'abc12345',
	// 	},
	// ],
	roleActions: [
		{ role: 'Administrador', actions: 'all' },
		{
			role: 'Gerencial',
			actions: [
				'get-bills-to-pay',
				'get-clients',
				'get-invoices',
				'get-invoices-configurations',
				'get-payments',
				'get-products',
				// 'get-reports',
				'get-sales',
				'get-sale',
				'get-scores',
				'get-users',
				'get-product-category',
				'register-bills-to-pay',
				'register-clients',
				'register-invoices',
				'register-products',
				'register-sales',
				'register-users',
				'register-product-category',
				'scores-find',
				'scores-history',
				'shipping-company-list',
				'shipping-company-register',
				// 'get-sales-by-consultant',
				//
			],
		},
		{
			role: 'Consultor',
			actions: [
				'get-products',
				'get-sales',
				'get-sale',
				'register-sales',
				'product-category',
				'register-product-category',
				'get-product-category',
			],
		},
	],
	salesTypes: [
		{ name: 'Venda', reference: 1 },
		{ name: 'Mensalidade', reference: 2 },
		{ name: 'Consultas', reference: 3 },
		{ name: 'Emissão de Notas Fiscais', reference: 4 },
	],
	paymentsTypes: [
		{ name: 'Crédito', reference: 1 },
		{ name: 'Débito', reference: 2 },
		{ name: 'Boleto', reference: 3 },
		{ name: 'Recorrência', reference: 4 },
		{ name: 'Link de Pagamento', reference: 5 },
		{ name: 'Cheque', reference: 6 },
		{ name: 'Dinheiro', reference: 7 },
		{ name: 'Pagamento no banco', reference: 8 },
		{ name: 'Transferência Bancária', reference: 9 },
	],
	banks: [
		{
			priority: 5,
			name: '001 - Banco do Brasil S.A.',
			cod: 1,
		},
		{
			priority: 5,
			name: '033 - Banco Santander (Brasil) S.A.',
			cod: 33,
		},
		{
			priority: 5,
			name: '341 - Itaú Unibanco S.A.',
			cod: 341,
		},
		{
			priority: 5,
			name: '237 - Banco Bradesco S.A.',
			cod: 237,
		},
		{
			priority: 5,
			name: '104 - Caixa Econômica Federal',
			cod: 104,
		},
		{
			priority: 100,
			name: '399 - HSBC Bank Brasil S.A. - Banco Múltiplo',
			cod: 399,
		},
		{
			priority: 100,
			name: '745 - Banco Citibank S.A.',
			cod: 745,
		},
		{
			priority: 100,
			name: '003 - Banco da Amazônia S.A.',
			cod: 3,
		},
		{
			priority: 100,
			name: '004 - Banco do Nordeste do Brasil S.A.',
			cod: 4,
		},
		{
			priority: 100,
			name: '012 - Banco Standard de Investimentos S.A.',
			cod: 12,
		},
		{
			priority: 100,
			name: '021 - BANESTES S.A. Banco do Estado do Espírito Santo',
			cod: 21,
		},
		{
			priority: 100,
			name: '024 - Banco BANDEPE S.A.',
			cod: 24,
		},
		{
			priority: 100,
			name: '025 - Banco Alfa S.A.',
			cod: 25,
		},
		{
			priority: 100,
			name: '029 - Banco Banerj S.A.',
			cod: 29,
		},
		{
			priority: 100,
			name: '031 - Banco Beg S.A.',
			cod: 31,
		},
		{
			priority: 100,
			name: '036 - Banco Bradesco BBI S.A.',
			cod: 36,
		},
		{
			priority: 100,
			name: '037 - Banco do Estado do Pará S.A.',
			cod: 37,
		},
		{
			priority: 100,
			name: '040 - Banco Cargill S.A.',
			cod: 40,
		},
		{
			priority: 100,
			name: '041 - Banco do Estado do Rio Grande do Sul S.A.',
			cod: 41,
		},
		{
			priority: 100,
			name: '045 - Banco Opportunity S.A.',
			cod: 45,
		},
		{
			priority: 100,
			name: '047 - Banco do Estado de Sergipe S.A.',
			cod: 47,
		},
		{
			priority: 100,
			name: '062 - Hipercard Banco Múltiplo S.A.',
			cod: 62,
		},
		{
			priority: 100,
			name: '063 - Banco Ibi S.A. Banco Múltiplo',
			cod: 63,
		},
		{
			priority: 100,
			name: '064 - Goldman Sachs do Brasil Banco Múltiplo S.A.',
			cod: 64,
		},
		{
			priority: 100,
			name: '065 - Banco AndBank (Brasil) S.A.',
			cod: 65,
		},
		{
			priority: 100,
			name: '069 - BPN Brasil Banco Múltiplo S.A.',
			cod: 69,
		},
		{
			priority: 100,
			name: '070 - BRB - Banco de Brasília S.A.',
			cod: 70,
		},
		{
			priority: 100,
			name: '073 - BB Banco Popular do Brasil S.A.',
			cod: 73,
		},
		{
			priority: 100,
			name: '074 - Banco J. Safra S.A.',
			cod: 74,
		},
		{
			priority: 100,
			name: '075 - Banco ABN AMRO S.A.',
			cod: 75,
		},
		{
			priority: 100,
			name: '077 - Banco Inter',
			cod: 77,
		},
		{
			priority: 100,
			name: '078 - BES Investimento do Brasil S.A.-Banco de Investimento',
			cod: 78,
		},
		{
			priority: 100,
			name: '082 - Banco Topázio',
			cod: 82,
		},
		{
			priority: 100,
			name: '084 - CC UNIPRIME NORTE DO PARANA',
			cod: 84,
		},
		{
			priority: 100,
			name: '085 - COOP CENTRAL AILOS',
			cod: 85,
		},
		{
			priority: 100,
			name: '090 - UNICRED MUTUO',
			cod: 90,
		},
		{
			priority: 100,
			name: '093 - Banco Polocred',
			cod: 93,
		},
		{
			priority: 100,
			name: '095 - Banco Confidence de Câmbio S.A.',
			cod: 95,
		},
		{
			priority: 100,
			name: '096 - Banco BM&FBOVESPA de Serviços de Liquidação e Custódia S.A',
			cod: 96,
		},
		{
			priority: 100,
			name: '107 - Banco BBM S.A.',
			cod: 107,
		},
		{
			priority: 100,
			name: '109 - Banco Zoop',
			cod: 109,
		},
		{
			priority: 100,
			name: '119 - Banco Western Union do Brasil S.A.',
			cod: 119,
		},
		{
			priority: 100,
			name: '125 - Brasil Plural S.A. - Banco Múltiplo',
			cod: 125,
		},
		{
			priority: 100,
			name: '133 - Banco Cresol',
			cod: 133,
		},
		{
			priority: 100,
			name: '136 - UNICRED',
			cod: 136,
		},
		{
			priority: 100,
			name: '144 - BEXS BANCO DE CAMBIO S.A.',
			cod: 144,
		},
		{
			priority: 100,
			name: '184 - Banco Itaú BBA S.A.',
			cod: 184,
		},
		{
			priority: 100,
			name: '197 - Stone Pagamentos',
			cod: 197,
		},
		{
			priority: 100,
			name: '208 - Banco BTG Pactual S.A.',
			cod: 208,
		},
		{
			priority: 100,
			name: '212 - Banco Original S.A.',
			cod: 212,
		},
		{
			priority: 100,
			name: '213 - Banco Arbi S.A.',
			cod: 213,
		},
		{
			priority: 100,
			name: '214 - Banco Dibens S.A.',
			cod: 214,
		},
		{
			priority: 100,
			name: '215 - Banco Comercial e de Investimento Sudameris S.A.',
			cod: 215,
		},
		{
			priority: 100,
			name: '217 - Banco John Deere S.A.',
			cod: 217,
		},
		{
			priority: 100,
			name: '218 - Banco Bonsucesso S.A.',
			cod: 218,
		},
		{
			priority: 100,
			name: '222 - Banco Credit Agricole Brasil S.A.',
			cod: 222,
		},
		{
			priority: 100,
			name: '224 - Banco Fibra S.A.',
			cod: 224,
		},
		{
			priority: 100,
			name: '233 - Banco Cifra S.A.',
			cod: 233,
		},
		{
			priority: 100,
			name: '237 - Banco Next',
			cod: 237,
		},
		{
			priority: 100,
			name: '248 - Banco Boavista Interatlântico S.A.',
			cod: 248,
		},
		{
			priority: 100,
			name: '249 - Banco Investcred Unibanco S.A.',
			cod: 249,
		},
		{
			priority: 100,
			name: '250 - BCV - Banco de Crédito e Varejo S.A.',
			cod: 250,
		},
		{
			priority: 100,
			name: '254 - Paraná Banco S.A.',
			cod: 254,
		},
		{
			priority: 5,
			name: '260 - Nu Bank',
			cod: 260,
		},
		{
			priority: 100,
			name: '263 - Banco Cacique S.A.',
			cod: 263,
		},
		{
			priority: 100,
			name: '265 - Banco Fator S.A.',
			cod: 265,
		},
		{
			priority: 100,
			name: '273 - Ccr De São Miguel Do Oeste',
			cod: 273,
		},
		{
			priority: 100,
			name: '274 - MONEY PLUS SOCIEDADE DE CRÉDITO',
			cod: 274,
		},
		{
			priority: 100,
			name: '280 - Banco AVISTA S.A. CFI',
			cod: 280,
		},
		{
			priority: 100,
			name: '290 - Pagseguro Internet S.A',
			cod: 290,
		},
		{
			priority: 100,
			name: '318 - Banco BMG S.A.',
			cod: 318,
		},
		{
			priority: 100,
			name: '320 - Banco Industrial e Comercial S.A.',
			cod: 320,
		},
		{
			priority: 100,
			name: '323 - Mercado Pago',
			cod: 323,
		},
		{
			priority: 100,
			name: '336 - Banco C6 Bank',
			cod: 336,
		},
		{
			priority: 100,
			name: '356 - Banco Real S.A.',
			cod: 356,
		},
		{
			priority: 100,
			name: '366 - Banco Société Générale Brasil S.A.',
			cod: 366,
		},
		{
			priority: 100,
			name: '370 - Banco Mizuho do Brasil S.A.',
			cod: 370,
		},
		{
			priority: 100,
			name: '376 - Banco J. P. Morgan S.A.',
			cod: 376,
		},
		{
			priority: 100,
			name: '389 - Banco Mercantil do Brasil S.A.',
			cod: 389,
		},
		{
			priority: 100,
			name: '396 - HUB Pagamentos',
			cod: 396,
		},
		{
			priority: 100,
			name: '403 - CORA SOCIEDADE DE CRÉDITO DIRETO S.A.',
			cod: 403,
		},
		{
			priority: 100,
			name: '409 - UNIBANCO - União de Bancos Brasileiros S.A.',
			cod: 409,
		},
		{
			priority: 100,
			name: '422 - Banco Safra S.A.',
			cod: 422,
		},
		{
			priority: 100,
			name: '456 - Banco de Tokyo-Mitsubishi UFJ Brasil S.A.',
			cod: 456,
		},
		{
			priority: 100,
			name: '464 - Banco Sumitomo Mitsui Brasileiro S.A.',
			cod: 464,
		},
		{
			priority: 100,
			name: '477 - Citibank S.A.',
			cod: 477,
		},
		{
			priority: 100,
			name: '487 - Deutsche Bank S.A. - Banco Alemão',
			cod: 487,
		},
		{
			priority: 100,
			name: '488 - JPMorgan Chase Bank',
			cod: 488,
		},
		{
			priority: 100,
			name: '492 - ING Bank N.V.',
			cod: 492,
		},
		{
			priority: 100,
			name: '505 - Banco Credit Suisse (Brasil) S.A.',
			cod: 505,
		},
		{
			priority: 100,
			name: '600 - Banco Luso Brasileiro S.A.',
			cod: 600,
		},
		{
			priority: 100,
			name: '604 - Banco Industrial do Brasil S.A.',
			cod: 604,
		},
		{
			priority: 100,
			name: '610 - Banco VR S.A.',
			cod: 610,
		},
		{
			priority: 100,
			name: '611 - Banco Paulista S.A.',
			cod: 611,
		},
		{
			priority: 100,
			name: '612 - Banco Guanabara S.A.',
			cod: 612,
		},
		{
			priority: 100,
			name: '623 - Banco PAN S.A.',
			cod: 623,
		},
		{
			priority: 100,
			name: '626 - Banco Ficsa S.A.',
			cod: 626,
		},
		{
			priority: 100,
			name: '630 - Banco Intercap',
			cod: 630,
		},
		{
			priority: 100,
			name: '633 - Banco Rendimento S.A.',
			cod: 633,
		},
		{
			priority: 100,
			name: '634 - Banco Triângulo S.A.',
			cod: 634,
		},
		{
			priority: 100,
			name: '641 - Banco Alvorada S.A.',
			cod: 641,
		},
		{
			priority: 100,
			name: '643 - Banco Pine S.A.',
			cod: 643,
		},
		{
			priority: 100,
			name: '653 - Banco Indusval S.A.',
			cod: 653,
		},
		{
			priority: 100,
			name: '655 - Banco Votorantim S.A.',
			cod: 655,
		},
		{
			priority: 100,
			name: '707 - Banco Daycoval S.A.',
			cod: 707,
		},
		{
			priority: 100,
			name: '719 - Banif-Banco Internacional do Funchal (Brasil)S.A.',
			cod: 719,
		},
		{
			priority: 100,
			name: '735 - Banco Neon',
			cod: 735,
		},
		{
			priority: 100,
			name: '739 - Banco Cetelem S.A.',
			cod: 739,
		},
		{
			priority: 100,
			name: '740 - Banco Barclays S.A.',
			cod: 740,
		},
		{
			priority: 100,
			name: '746 - Banco Modal S.A.',
			cod: 746,
		},
		{
			priority: 100,
			name: '747 - Banco Rabobank International Brasil S.A.',
			cod: 747,
		},
		{
			priority: 100,
			name: '748 - Banco Cooperativo Sicredi S.A.',
			cod: 748,
		},
		{
			priority: 100,
			name: '751 - Scotiabank Brasil S.A. Banco Múltiplo',
			cod: 751,
		},
		{
			priority: 100,
			name: '752 - Banco BNP Paribas Brasil S.A.',
			cod: 752,
		},
		{
			priority: 100,
			name: '755 - Bank of America Merrill Lynch Banco Múltiplo S.A.',
			cod: 755,
		},
		{
			priority: 100,
			name: '756 - Banco Cooperativo do Brasil S.A. - BANCOOB',
			cod: 756,
		},
		{
			priority: 100,
			name: '779 - Banco Intermedium S.A.',
			cod: 779,
		},
		{
			priority: 100,
			name: '10001 - Zoop BPP - Brasil Pré Pago',
			cod: 10001,
		},
	],
	menus: [
		{
			title: 'Clientes',
			url: 'plataforma/clientes',
			parent: null,
			action: 'get-clients',
			icon: '/media/icons/duotone/Communication/Group.svg',
		},
		{
			title: 'Produtos',
			url: 'plataforma/produtos',
			parent: null,
			action: 'get-products',
			icon: '/media/icons/duotone/Home/Bed.svg',
		},
		{
			title: 'Consulta Score',
			url: 'plataforma/consulta-score',
			parent: null,
			action: 'get-scores',
			icon: '/media/icons/duotone/Shopping/Chart-pie.svg',
		},
		{
			title: 'Contas à pagar',
			url: 'plataforma/contas-a-pagar',
			parent: null,
			action: 'get-bills-to-pay',
			icon: '/media/icons/duotone/Shopping/Barcode.svg',
		},
		{
			title: 'Estabelecimentos',
			url: 'plataforma/consultor-master',
			parent: null,
			action: 'get-users-pre-register',
			icon: '/media/icons/duotone/Home/Building.svg',
		},
		{
			title: 'Transportadoras',
			url: 'plataforma/transportadoras',
			parent: null,
			action: 'ShippingCompany',
			icon: '/media/icons/duotone/Navigation/Route.svg',
		},
		{
			title: 'Consultores',
			url: 'plataforma/consultores',
			parent: null,
			action: 'get-users',
			icon: '/media/icons/duotone/Clothes/Briefcase.svg',
		},
		{
			title: 'Vendas',
			url: 'plataforma/vendas',
			parent: null,
			action: 'get-sales',
			icon: '/media/icons/duotone/Shopping/Dollar.svg',
		},
		{
			title: 'Realizar consulta',
			url: 'plataforma/consulta-score/realizar-consulta',
			parent: 'plataforma/consulta-score',
			action: 'scores-find',
			icon: null,
		},
		{
			title: 'Listagem',
			url: 'plataforma/contas-a-pagar/listagem',
			parent: 'plataforma/contas-a-pagar',
			action: 'get-bills-to-pay',
			icon: null,
		},
		{
			title: 'Consultas realizadas',
			url: 'plataforma/consulta-score/consultas-realizadas',
			parent: 'plataforma/consulta-score',
			action: 'scores-history',
			icon: null,
		},
		{
			title: 'Cadastrar',
			url: 'plataforma/produtos/cadastrar',
			parent: 'plataforma/produtos',
			action: 'register-products',
			icon: null,
		},
		{
			title: 'Pré Cadastro',
			url: 'plataforma/consultor-master/pre-cadastro',
			parent: 'plataforma/consultor-master',
			action: 'approve-pre-register',
			icon: null,
		},
		{
			title: 'Listagem',
			url: 'plataforma/consultor-master/listagem',
			parent: 'plataforma/consultor-master',
			action: 'get-users-pre-register',
			icon: null,
		},
		{
			title: 'Cadastrar',
			url: 'plataforma/clientes/adicionar',
			parent: 'plataforma/clientes',
			action: 'register-clients',
			icon: null,
		},
		{
			title: 'Listagem',
			url: 'plataforma/clientes/listagem',
			parent: 'plataforma/clientes',
			action: 'get-clients',
			icon: null,
		},
		{
			title: 'Listagem',
			url: 'plataforma/produtos/listagem',
			parent: 'plataforma/produtos',
			action: 'get-products',
			icon: null,
		},
		{
			title: 'Cadastrar',
			url: 'plataforma/vendas/cadastrar',
			parent: 'plataforma/vendas',
			action: 'register-sales',
			icon: null,
		},
		{
			title: 'Listagem',
			url: 'plataforma/consultores/listagem',
			parent: 'plataforma/consultores',
			action: 'get-users',
			icon: null,
		},
		{
			title: 'Cadastrar',
			url: 'plataforma/contas-a-pagar/cadastrar',
			parent: 'plataforma/contas-a-pagar',
			action: 'register-bills-to-pay',
			icon: null,
		},
		{
			title: 'Listar',
			url: 'plataforma/transportadoras/listar',
			parent: 'plataforma/transportadoras',
			action: 'shipping-company-list',
			icon: null,
		},
		{
			title: 'Cadastrar',
			url: 'plataforma/consultores/ccadastrar',
			parent: 'plataforma/consultores',
			action: 'register-users',
			icon: null,
		},
		{
			title: 'Listagem',
			url: 'plataforma/vendas/listagem',
			parent: 'plataforma/vendas',
			action: 'get-sales',
			icon: null,
		},
		{
			title: 'Cadastrar',
			url: 'plataforma/transportadoras/cadastrar',
			parent: 'plataforma/transportadoras',
			action: 'shipping-company-register',
			icon: null,
		},
		{
			title: 'Configurações',
			url: 'plataforma/consulta-score/configuracoes',
			parent: 'plataforma/consulta-score',
			action: 'get-scores-configurations',
			icon: null,
		},
		{
			title: 'Relatórios',
			url: 'plataforma/relatorios',
			parent: null,
			action: 'get-reports',
			icon: '/media/icons/duotone/Interface/File.svg',
		},
		{
			title: 'Vendas por Vendedor',
			url: 'plataforma/relatorios/vendas-por-vendedor',
			parent: 'plataforma/relatorios',
			action: 'get-reports',
			icon: null,
		},
	],
};
